In [30]:
import numpy as np
import pandas as pd
from math import sqrt
#https://scipy-lectures.org/intro/numpy/array_object.html

In [31]:
#Construct a shape (100,) boolean array is_prime, filled with True in the beginning:

In [32]:
# true == 1, so np.ones or np.empty (creates uninitialized array):
# is_prime = np.empty((20+1), dtype=bool)
is_prime = np.ones(20+1, dtype=bool)

In [33]:
print(is_prime)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True]


In [34]:
# Initial values
    # Cross out 0 and 1 which are not primes:
is_prime[0:2] = False
is_prime[2:] = True #all the rest

In [35]:
is_prime

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [36]:
#For each integer j starting from 2, cross out its higher multiples:

In [37]:
N_max = int(np.sqrt(len(is_prime) - 1))
for j in range(2, N_max):
    is_prime[2*j::j] = False

# # Prints your primes
print("==> Primes through 20:\n", np.nonzero(is_prime))
# np.nonzero(is_prime)

==> Primes through 20:
 (array([ 2,  3,  5,  7, 11, 13, 17, 19]),)


In [38]:
def sieve(n):
    """
    Returns the prime number 'sieve' shown above.
    
    That is, this function returns an array `X[0:n+1]`
    such that `X[i]` is true if and only if `i` is prime.
    """
    
    #Construct a shape (100,) boolean array is_prime, filled with True in the beginning:
    #is_prime = np.ones((100,), dtype=bool)
    
    is_prime = np.empty(n+1, dtype=bool) # the "sieve"

    # Initial values
    # Cross out 0 and 1 which are not primes:
    is_prime[0:2] = False # {0, 1} are _not_ considered prime
    is_prime[2:] = True # All other values might be prime

    # Implement the sieving loop
    
    ### START SOLUTION
    
    #For each integer j starting from 2, cross out its higher multiples:
    N_max = int(np.sqrt(len(is_prime) - 1))
    for j in range(2, N_max + 1):
        is_prime[2*j::j] = False
    
    return is_prime

# Prints your primes
print("==> Primes through 20:\n", np.nonzero(sieve(20))[0])

==> Primes through 20:
 [ 2  3  5  7 11 13 17 19]
