In [1]:
import numpy as np

# random numbers / reshape

In [2]:
r = np.random.random(6000)

In [3]:
r.size

6000

In [4]:
r.shape #1D vector

(6000,)

In [6]:
#convert to matrix: 
r_matrix = r.reshape(200,30)

In [11]:
print("shape:",r_matrix.shape, "\nsize:", r_matrix.size)

shape: (200, 30) 
size: 6000


In [12]:
r_matrix.sum()

2971.3806260912743

In [13]:
np.sum(r_matrix)

2971.3806260912743

In [16]:
np.sum(r_matrix, axis=0).size #col

30

In [17]:
np.sum(r_matrix, axis=1).size #row

200

In [20]:
r_matrix.sum(axis=1).shape

(200,)

### create a numpy array with random numbers and get numbers closest to .50

In [64]:
s = np.random.random(25)
s

array([0.18710243, 0.93374443, 0.12416209, 0.63443779, 0.11743192,
       0.68605553, 0.82437881, 0.41885417, 0.36216852, 0.78426387,
       0.7461921 , 0.22796459, 0.72944335, 0.04040273, 0.21701983,
       0.03559436, 0.86954909, 0.26215626, 0.51140649, 0.82660761,
       0.90443973, 0.12743764, 0.54995867, 0.63884941, 0.9267787 ])

In [65]:
s.shape #vector 

(25,)

# reshape step

In [66]:
s = s.reshape(5,5) #vector convert to matrix form 
s

array([[0.18710243, 0.93374443, 0.12416209, 0.63443779, 0.11743192],
       [0.68605553, 0.82437881, 0.41885417, 0.36216852, 0.78426387],
       [0.7461921 , 0.22796459, 0.72944335, 0.04040273, 0.21701983],
       [0.03559436, 0.86954909, 0.26215626, 0.51140649, 0.82660761],
       [0.90443973, 0.12743764, 0.54995867, 0.63884941, 0.9267787 ]])

### dist50

In [67]:
s - .5

array([[-0.31289757,  0.43374443, -0.37583791,  0.13443779, -0.38256808],
       [ 0.18605553,  0.32437881, -0.08114583, -0.13783148,  0.28426387],
       [ 0.2461921 , -0.27203541,  0.22944335, -0.45959727, -0.28298017],
       [-0.46440564,  0.36954909, -0.23784374,  0.01140649,  0.32660761],
       [ 0.40443973, -0.37256236,  0.04995867,  0.13884941,  0.4267787 ]])

In [68]:
dist50 = np.abs(s - 0.5) #get absolute distance of the data
dist50

array([[0.31289757, 0.43374443, 0.37583791, 0.13443779, 0.38256808],
       [0.18605553, 0.32437881, 0.08114583, 0.13783148, 0.28426387],
       [0.2461921 , 0.27203541, 0.22944335, 0.45959727, 0.28298017],
       [0.46440564, 0.36954909, 0.23784374, 0.01140649, 0.32660761],
       [0.40443973, 0.37256236, 0.04995867, 0.13884941, 0.4267787 ]])

### position where closest to .50

In [69]:
#which in index closest to .5???
np.argmin(dist50, axis=0) #location along column

array([1, 2, 4, 3, 2])

### position overall where closest to .50

In [70]:
np.argmin(dist50)

18