### Playground

In [44]:
import pandas as pd
import numpy as np

In [47]:
a = np.array([[1,2,3], [4,5,6]])
print("shape:",a.shape)
print("dimensions:",a.ndim)
# np.reshape(a, 6)
# array([1, 2, 3, 4, 5, 6])

shape: (2, 3)
dimensions: 2


In [48]:
a2 = np.reshape(a,6) #2d to 1d
print("shape:",a2.shape)
print("dimensions:",a2.ndim)

shape: (6,)
dimensions: 1


In [49]:
a2.shape

(6,)

In [50]:
from numpy.random import default_rng
rng = default_rng()

A = rng.integers(-10, 10, size=(4, 3)) # return random integers from -10 (inclusive) to 10 (exclusive)
print(A)

[[-4  4  7]
 [-2  1 -7]
 [-6  8 -3]
 [ 0  0 -2]]


In [51]:
A_row_means = np.mean(A, axis=0)

print(A, "\n=>\n", A_row_means) #column means

[[-4  4  7]
 [-2  1 -7]
 [-6  8 -3]
 [ 0  0 -2]] 
=>
 [-3.    3.25 -1.25]


In [52]:
A_row_centered = A - A_row_means
A_row_centered

array([[-1.  ,  0.75,  8.25],
       [ 1.  , -2.25, -5.75],
       [-3.  ,  4.75, -1.75],
       [ 3.  , -3.25, -0.75]])

In [53]:
A_col_means = np.mean(A, axis=1)

print(A, "\n=>\n", A_col_means)

[[-4  4  7]
 [-2  1 -7]
 [-6  8 -3]
 [ 0  0 -2]] 
=>
 [ 2.33333333 -2.66666667 -0.33333333 -0.66666667]


In [54]:
A - A_col_means

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [55]:
print(A.shape, A_row_means.shape)

(4, 3) (3,)


In [56]:
print(A.shape, A_col_means.shape)

(4, 3) (4,)


In [59]:
A_col_means2 = np.reshape(A_col_means, (len(A_col_means), 1))
print(A_col_means2, "=>", A_col_means2.shape)

[[ 2.33333333]
 [-2.66666667]
 [-0.33333333]
 [-0.66666667]] => (4, 1)


In [61]:
A - A_col_means2

array([[-6.33333333,  1.66666667,  4.66666667],
       [ 0.66666667,  3.66666667, -4.33333333],
       [-5.66666667,  8.33333333, -2.66666667],
       [ 0.66666667,  0.66666667, -1.33333333]])