### Playground

In [2]:
import pandas as pd
import numpy as np

# 2D to 1D reshape

In [12]:
a = np.array([[1,2,3], [4,5,6]])
print("shape:",a.shape)
print("dimensions:",a.ndim)

shape: (2, 3)
dimensions: 2


In [4]:
a2 = np.reshape(a,6) #2d to 1d
print("shape:",a2.shape)
print("dimensions:",a2.ndim)

shape: (6,)
dimensions: 1


In [5]:
a2.shape

(6,)

# np.reshape(-1,1)
## len(a) vs -1 vs .shape[0]

In [7]:
X = np.array([1,2,3])
print("shape:",X.shape) #vector
print("dimensions:",X.ndim)

shape: (3,)
dimensions: 1


In [10]:
X1 = X.reshape(len(X), 1)
print("shape:",X1.shape) #vector -> matrix using len(X)
print("dimensions:",X1.ndim)

shape: (3, 1)
dimensions: 2


In [11]:
X2 = X.reshape(-1, 1)
print("shape:",X2.shape) #vector -> matrix using -1 (when don't know how many rows we have..)
print("dimensions:",X2.ndim)

shape: (3, 1)
dimensions: 2


# A_row_centered = A - A_row_means; A_col_centered shape issue..

In [13]:
from numpy.random import default_rng
rng = default_rng()

A = rng.integers(-10, 10, size=(4, 3)) # return random integers from -10 (inclusive) to 10 (exclusive)
print(A)

[[ 7 -7  9]
 [ 8  2  0]
 [-4  4  1]
 [-6 -9 -1]]


In [14]:
A_row_means = np.mean(A, axis=0)

print(A, "\n=>\n", A_row_means) #column means

[[ 7 -7  9]
 [ 8  2  0]
 [-4  4  1]
 [-6 -9 -1]] 
=>
 [ 1.25 -2.5   2.25]


In [15]:
A_row_centered = A - A_row_means
A_row_centered

array([[ 5.75, -4.5 ,  6.75],
       [ 6.75,  4.5 , -2.25],
       [-5.25,  6.5 , -1.25],
       [-7.25, -6.5 , -3.25]])

In [16]:
A_col_means = np.mean(A, axis=1)

print(A, "\n=>\n", A_col_means)

[[ 7 -7  9]
 [ 8  2  0]
 [-4  4  1]
 [-6 -9 -1]] 
=>
 [ 3.          3.33333333  0.33333333 -5.33333333]


In [17]:
A - A_col_means

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [18]:
print(A.shape, A_row_means.shape)

(4, 3) (3,)


In [19]:
print(A.shape, A_col_means.shape)

(4, 3) (4,)


In [22]:
A_col_means2 = np.reshape(A_col_means, (A_col_means.shape[0], 1)) #len(A_col_means) vs -1 vs .shape[0]
print(A_col_means2, "=>", A_col_means2.shape)

[[ 3.        ]
 [ 3.33333333]
 [ 0.33333333]
 [-5.33333333]] => (4, 1)


In [23]:
A - A_col_means2

array([[  4.        , -10.        ,   6.        ],
       [  4.66666667,  -1.33333333,  -3.33333333],
       [ -4.33333333,   3.66666667,   0.66666667],
       [ -0.66666667,  -3.66666667,   4.33333333]])