### Exercise to find random number in array that is closest to 0.75
Generate a 10 x 3 array of random numbers. From each row, pick the number closest to 0.75. 
- Make use of `np.abs` and `np.argmin` to find the column j which contains the closest element in each row. The final result should be a vector of shape (10,).
- https://github.com/jni/scipy-japan-2019/blob/master/Advanced%20NumPy%20Patterns%20Solved.ipynb

In [17]:
import pandas as pd
import numpy as np

In [18]:
arr = np.random.random((10,3)) 
print(rand) #<class 'numpy.ndarray'>

[[0.83888101 0.11681351 0.25379449]
 [0.04350057 0.94501905 0.93086826]
 [0.6610606  0.82460235 0.47889412]
 [0.48195005 0.97147805 0.62951074]
 [0.40884307 0.32692084 0.6630802 ]
 [0.14773956 0.25357539 0.35842251]
 [0.37914274 0.39294166 0.03462409]
 [0.47646374 0.51837595 0.92807624]
 [0.06249777 0.62796339 0.04189638]
 [0.07730699 0.39331216 0.00665617]]


In [19]:
# np.argmin is position of min along an array
# 10 random numbers, want number closest to 0.75 per row

In [20]:
#distance from every number to 0.75 in the matrix:
dist75 = np.abs(arr - 0.75)
print(dist75)

[[0.19123765 0.17314919 0.02099066]
 [0.02516548 0.06644262 0.05506866]
 [0.04680132 0.66260759 0.36358385]
 [0.22663667 0.46482601 0.61086014]
 [0.45744804 0.08374571 0.12928087]
 [0.05928417 0.19957409 0.69017811]
 [0.14157494 0.42756975 0.02765956]
 [0.0694065  0.59963327 0.24095228]
 [0.6278918  0.16035859 0.40215627]
 [0.15704862 0.03005279 0.09022196]]


In [21]:
np.argmin? 
#Signature: np.argmin(a, axis=None, out=None)
#Docstring:
#Returns the indices of the minimum values along an axis.

SyntaxError: invalid syntax (<ipython-input-21-3fb3ae75e781>, line 1)

## argmin with axis = 0

In [22]:
np.argmin(dist75) #gives single location of smallest value in entire matrix

2

## argmin with axis = 1

In [23]:
np.argmin(dist75, axis=1) #gives location per row

array([2, 0, 0, 0, 1, 0, 2, 0, 1, 1])

### Exercise finding variance across rows, using argsort: 
Some applications, such as clustering, are computationally expensive, and wouldn't work without first doing some form of feature selection, where we discard most of the data and keep only what we think will be most useful. One simple version is to keep only the genes with the most variance (as these will be more informative than genes that don't vary between patients).

Find the variance across patients of all the genes (rows) in the expression dataset.
Use np.argsort to find the location of the 1,500 most variable genes.
Use these indices to produce a shape (1500, 375) matrix containing only the most variable genes.

In [26]:
# if row doesn't vary much and is flat it might not yield any info
# so we can not include in analysis
#higher variance might be more useful.. 

In [27]:
np.var?

In [28]:
# row_variance = np.var(expr, axis=1)

In [29]:
# row_variance.shape  
#(20500,) so it gives one value of variance per row

In [30]:
#find the most variable ones: the location
np.argsort? #Returns the indices (in array) that would sort an array

In [31]:
# row_variance_order = np.argsort(row_variance) #values smallest to biggest

In [32]:
# most_variable_rows = row_variance_order[-1500:] #1500 most variable

In [33]:
# most_variable_data = expr[most_variable_rows]

In [ ]:
#most_variable_data.shape
#(1500, 375) which is the right shape!! 